### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

In [18]:
import  numpy as  np

# Create an ndarray object 'A' from a nested Python list with values between 1 and 100.
#  This variable uses values from 2 to 30.
A = np.array([[2, 4], [6, 8],[10, 12], [14, 16], [18, 20], [22, 24], [26, 30],])

# 1. Using a property of the ndarray object
# A.shape the size of dimensions the array. In this case, (7, 2) means 7 rows and 2 columns.
display(A.shape)

# 2. Using a method of the ndarray object
# A.max() is a method that returns the maximum value in the array.
display(A.max())

# 3. Using a numpy function and passing an ndarray
# np.min(A) is a NumPy function that also returns the minimum value in the array.
# This uses a function from the numpy module directly.
display(np.min(A))

(7, 2)

np.int64(30)

np.int64(2)

### Exercise

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

In [32]:
import numpy as np

# B. Create a 5x5 integer-array filled with ones.
# np.ones((5, 5), dtype=int) creates a two-dimensional array with 5 rows and 5 columns,
# where all elements are the integer value 1.
B = np.ones((5, 5), dtype=int)

# Display the array B to show its contents.
display(B)
# Check the shape of the array.
# B.shape returns a tuple representing the dimensions of the array. For a 5x5 array, this will be (5, 5).
display(B.shape)

# Check the size of the array.
# B.size returns the total number of elements in the array. For a 5x5 array, this is 25.
display(B.size)

# Check the number of dimensions of the array.
# B.ndim returns an integer indicating how many dimensions the array has. For a 2D array, this is 2.
display(B.ndim)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

(5, 5)

25

2

### Exercise

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [38]:
import numpy as np

# np.arange(-5, 6, 1) creates an array of integers starting from -5 up to (but not including) 6.
# This results in an array [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5].
C = np.arange(-5, 6, 1) # This line creates an array from -5 to 5 with a step of 1.

# Multiply each value in the array by 2.
# NumPy allows direct element-wise multiplication on arrays.
Cx2 = C * 2

# Print the resulting array.
display(C)
display(Cx2)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])